spring:
  datasource:
    url: jdbc:postgresql://localhost:9000/leetcode
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080